### ISSUE TITLE
babel-eslint

### ISSUE THREAD

**Issue by kof** [feross/eslint-config-standard#12]
Can we make it work with babel-eslint so that experimental features like decorators can pass?

**Comment by kof** [comment]
https://github.com/babel/babel-eslint

**Comment by dcousens** [comment]
Doesn't it already?

**Comment by kof** [comment]
Not for me)

**Comment by dcousens** [comment]
https://github.com/feross/standard/blob/4a7e0306dda66825326cd5e2978145330b04dc3e/README.md#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support

**Comment by kof** [comment]
missed that, thanks!

**Comment by dcousens** [comment]
No worries @kof,  move visibility in terms of issues is always good!
