### ISSUE TITLE
Warning for style

### ISSUE THREAD

**Issue by denis-sokolov** [feross/eslint-config-standard#13]
Is there a design decision on why the warnings feature of eslint is not used? One could consider marking only the real error-catching rules as errors, and the rest of styling distinctions as warnings.

This allows the users to prioritize efforts on fixing errors first, and the style second. More importantly, the currently proposed best practice of running `standard` as part of `npm test` results in quick test cycle (i.e. TDD) users being highly annoyed, as it is impossible to iterate quickly if every tiny styling issue breaks the tests. Warnings would not affect the return code, resulting in a better experience.

**Comment by denis-sokolov** [comment]
Disregard that, did not find feross/standard#108 before, sorry.

**Comment by feross** [comment]
No problem. Thanks for opening a thoughtful issue. :)

**Comment by marcinn** [comment]
I read the docs and this discussion. Just want to say that "All rules should be errors" is an insane rule. This makes "the standard/standard" unusable on the battlefield. You want to shoot an enemy, but your gun says "error, wrong finger". Nah.
