### ISSUE TITLE
what is you opinion regarding ES2015 rules?

### ISSUE THREAD

**Issue by jokeyrhyme** [feross/eslint-config-standard#14]
I noticed that there are few ES2015 rules that you have not set: http://eslint.org/docs/rules/#ecmascript-6

I assume it's because these rules are not compatible with ES5 code, and this shared config straddles both ES5 and ES2015. Is there a way to split this shared config into separate ES5 and ES2015 projects, sort of like I have?
- https://github.com/jokeyrhyme/eslint-config-es5
- https://github.com/jokeyrhyme/eslint-config-es2015

Anyway, back on topic, if you knew your shared config was only going to be used on ES2015 projects, which of these addition ES2015 ESLint rules would to enable? What does JavaScript Standard Code Style look like in an ES2015 world?

**Comment by jokeyrhyme** [comment]
Specifically, your config lacks:
- arrow-parens
- no-var
- object-shorthand
- prefer-arrow-callback
- prefer-const
- prefer-spread
- prefer-reflect
- prefer-template
- require-yield

I'm just wondering if this is intentional or if you've skipped them for now for compatibility reasons. Cheers!

**Comment by sindresorhus** [comment]
In [XO](https://github.com/sindresorhus/xo) I have a separate [sub-config](https://github.com/sindresorhus/eslint-config-xo/blob/master/esnext.js) for `esnext` type rules that are incompatible with ES5 and a [`esnext` option](https://github.com/sindresorhus/xo/#esnext) in the CLI. Might be a good idea for Standard too.

**Comment by dcousens** [comment]
@jokeyrhyme it is my understanding these options have been skipped for compatibility reasons.
If we can detect that ES6 is in use reliably (without a configuration option) we might turn them on.

**Comment by jokeyrhyme** [comment]
I did try to submit this to ESLint, but the contributors determined that this would confuse users: https://github.com/eslint/eslint/issues/3686 https://github.com/eslint/eslint/pull/3696

@dcousens I think ESLint configs are too static to be able to do that sort of switching. I think the best solution for now is to maintain separate shared configs.

I currently maintain my own separate ES2015 config, so I was wondering what I should have there to maintain the JavaScript Standard Code Style spirit?

**Comment by dcousens** [comment]
There was a discussion in https://github.com/feross/standard/issues/159.

@feross maybe we should decide what these rules will be ahead of time?

**Comment by Flet** [comment]
![giphy](https://cloud.githubusercontent.com/assets/360233/9870338/b90c525a-5b50-11e5-8820-a93a080bb55e.gif)

Could create a standard es2015 eslint config that extends this config then make a standard-next CLI tool using standard-engine.

**Comment by dcousens** [comment]
@Flet I can foresee a `standard-next` in your published package lists.

**Comment by feross** [comment]
Honestly, at this point I think we should just add a `--next` flag for people who write ES6.

In a year or two when everyone has upgraded to node v4.0.0 and ES6 browser support is pervasive, we can make it the default.

**Comment by dcousens** [comment]
@feross I'm in favour of that to be honest,  but,  only because this is a transitional period.
Maybe put in a clear number of major versions for which it will exist (and or a time limit)?

**Comment by julien-f** [comment]
I think standard should use a rolling-release style for the `--esnext` flag: it should always enable rules related to ES versions still unreleased or released less than a year ago (for instance).

**Comment by sindresorhus** [comment]
> it should always enable rules related to ES versions still unreleased or released less than a year ago (for instance).

:+1: That's how I do it.

**Comment by dcousens** [comment]
This will make the editor plugins a tad more frustrating to have by default.

**Comment by Flet** [comment]
The seed for all these ideas will probably be creating a separate `eslint-config-standard-esnext` package to get the rules defined :smile:

**Comment by jokeyrhyme** [comment]
@Flet it probably also means dropping then `env.es6: true` and `ecmaFeatures` directives from this config, and moving them to standard-esnext?

**Comment by gotofritz** [comment]
I think the only sane solution for the time being is to give different files different suffixes (.js and .es6 say) split the config into two files (shared and es6 specific), and use some gulp (grunt, whatever) magic to apply ES5 settings .js files and ES5 + ES6 settings to .es6 files.

**Comment by dcousens** [comment]
> .js and .es6 say

Not going to happen.

**Comment by gotofritz** [comment]
What is not going to happen? I didn't ask you to do anything. Was just suggesting a workflow to get around the problem. 

Also, I got here from a link in an issue in the eslint repo - didn't even realise it was a different project. I hate JS "standard" style and it's non standard semi-colon bullshit, so I'll leave you guys to it.

**Comment by dcousens** [comment]
@gotofritz sorry, that might have come across as a stand offish.
I meant in the general standard community, asking users to rename files and consequently update their editors and testing flow etc etc,  just for linting,  isn't really a good work around.

**Comment by gotofritz** [comment]
No problem. It's not that unusual - in our projects we use the .jsx suffix to give less work to Babel for example. But anyway, it was just a suggestion.

**Comment by dcousens** [comment]
@feross I believe these rules have been addressed now?

**Comment by feross** [comment]
Yeah, I think we're not going to do anything about these rules for now.
