### ISSUE TITLE
Error: eslint-config-standard: Configuration for rule "generator-star-spacing" is invalid

### ISSUE THREAD

**Issue by mfn** [feross/eslint-config-standard#17]
I'm already using babel/eslint for a project and added eslint-config-standard with `npm install --save--dev eslint-config-standard`.

Adjusted my `.eslintrc` to extend `standard` and was hit by this
```
$ node_modules/.bin/eslint  src/
/vagrant/node-project/node_modules/eslint/lib/config.js:129
                    throw e;
                    ^

Error: eslint-config-standard:
        Configuration for rule "generator-star-spacing" is invalid:
        Value "[object Object]" must be an enum value.

Referenced from: /vagrant/node-project/.eslintrc
    at validateRuleOptions (/vagrant/node-project/node_modules/eslint/lib/config-validator.js:88:15)
    at /vagrant/node-project/node_modules/eslint/lib/config-validator.js:101:13
    at Array.forEach (native)
    at Object.validate (/vagrant/node-project/node_modules/eslint/lib/config-validator.js:100:35)
    at loadConfig (/vagrant/node-project/node_modules/eslint/lib/config.js:99:19)
    at /vagrant/node-project/node_modules/eslint/lib/config.js:123:46
    at Array.reduceRight (native)
    at loadConfig (/vagrant/node-project/node_modules/eslint/lib/config.js:111:36)
    at getLocalConfig (/vagrant/node-project/node_modules/eslint/lib/config.js:225:23)
    at Config.getConfig (/vagrant/node-project/node_modules/eslint/lib/config.js:363:22)
```
Tried to be clever and changed `generator-star-spacing` to simply 2 in `node_modules/eslint-config-standard/eslintrc.json` for testing, but then was hit by the next error:
```
Error: eslint-config-standard:
        Configuration for rule "indent" is invalid:
        Value "data["2"].SwitchCase" has additional properties.
```

Installing this package gave me `1.3.1`; I'm using babel `5.8.29` and `3.1.30` -> is there any known incompatibility?

**Comment by feross** [comment]
What version of eslint are you using? This looks to me like you're using an old version of eslint. Our configuration is probably using rules that your version of eslint doesn't know about.

Please try updating eslint.

**Comment by mfn** [comment]
eslint `0.23.0`; I see it's quite outdated. Let's close this then.

However: any way to know which version is supported, i.e. version constraints or something?

**Comment by feross** [comment]
The config depends on the latest 1.0.0 version of eslint.

We used to enforce this with a peer dependency, but it wasn't really the right thing for the situation. For example, `standard` depends on `standard-engine` instead of `eslint` (`standard-engine` itself requires `eslint`).
