### ISSUE TITLE
Unmet peer dependency while installing

### ISSUE THREAD

**Issue by nfantone** [feross/eslint-config-standard#20]
Installing this module on `npm 3.5.4` gives:

```
$ npm install --save-dev eslint-config-standard
project@0.0.1 /home/nfantone/dev/js/project
├── eslint-config-standard@4.4.0 
└── UNMET PEER DEPENDENCY eslint-plugin-standard@^1.1.0

npm WARN eslint-config-standard@4.4.0 requires a peer of eslint-plugin-standard@^1.1.0 but none was installed.
```

Which forced me to manually install `eslint-plugin-standard`. Any chance this `peerDependency` could be moved to `dependencies`, instead?

**Comment by jokeyrhyme** [comment]
To function correctly, both eslint-plugin-standard and eslint-config-standard need to be top-level dependencies, directly `require()`-able from the context of the consuming project. This is the desired state we need to be in for eslint to find both the plugin and the config.

With npm 2, the way to accomplish this was with the peerDependencies list. Your suggestion would cause breakage for any npm 2 users that depend on this project. But, is npm 2 still supported by this project?

npm 3 installs to a flat tree. So your suggestion to change eslint-plugin-standard from a peerDependency to a dependency of this project would theoretically get us to the desired state. However, npm 3 nests dependencies (as in npm 2) when there are version conflicts. When this occurs, the version of eslint-plugin-standard that is directly `require()`-able may not be a version that is compatible with the installed version of this project.

So, your suggestion seems like a good solution, unless either of these conditions is true:
- this project still aims to support npm 2 users
- this project cares about the potentially unlikely scenario of a eslint-plugin-standard version conflict

**Comment by nfantone** [comment]
Well explained, @jokeyrhyme.

So, the alternative boils down to "go copy `peerDependencies` and its specific version from this repo's `package.json` and paste them in your as `devDependencies`".  You still have to worry about version conflicts this way, though.

**Comment by bshack** [comment]
Looks like this bug affects npm shrinkwrap, it will not allow project to be shrinkwraped

**Comment by jokeyrhyme** [comment]
This isn't a bug. It's the way npm is designed to function:
http://blog.npmjs.org/post/110924823920/npm-weekly-5

As far as supporting this goes, @nfantone nails it:

> So, the alternative boils down to "go copy `peerDependencies` and its specific versions from this repo's `package.json` and paste them in yours as `devDependencies`".

**Comment by feross** [comment]
Yeah, sadly this is due to how `eslint` wants plugins to work. You, the user, needs to know all the plugins that your config is using and manually install them. :(

The fact that things worked out nicely was because npm2 would install peer dependencies for you. That's not the case in npm3.

If you want to join the discussion on the eslint issue tracker, it's here: https://github.com/eslint/eslint/issues/3458
