### ISSUE TITLE
Breaking changes coming with eslint 2

### ISSUE THREAD

**Issue by neverfox** [feross/eslint-config-standard#22]
Just a heads up that there are a lot of rules being deprecated in 2.0.0. Is an upgrade planned?

**Comment by jaydenseric** [comment]
After upgrading eslint to `2.0.0-beta.3` I'm getting a lot of errors relating to a `keyword-spacing` rule replacing several deprecated rules.

**Comment by feross** [comment]
Yes, the version on `master` should work with 2.0.0 today. We'll do a release to npm very soon.

**Comment by feross** [comment]
New version has been published that works with eslint 2.0.0.
