### ISSUE TITLE
no-constant-condition rule doubt

### ISSUE THREAD

**Issue by ifraixedes** [feross/eslint-config-standard#33]
I'd like to know if `no-constant-condition` has been considered to be added because it isn't a formatting rule and can help to detect buggy code.

http://eslint.org/docs/rules/no-constant-condition

I'm not trying to convince to add it, I'm just wondering if it has been missed than discarded.

Thanks

**Comment by feross** [comment]
I think we may have had `no-constant-condition` in the past, but it was removed because it prevented valid code like this from passing:

```js
var x = 1
while (true) {
  x++
  if (x === 10) break
}
```

That's a contrived example, but doing `while (true)` plus a break is actually quite common in certain low-level libraries.

Thanks for opening the issue!

**Comment by dcousens** [comment]
The `while (true)` example also allows for conditional locality,  such that the logic for ending the loop isn't forced to be at the start but during the control flow with which it might be relevant. :+1:

**Comment by ifraixedes** [comment]
I was thinking in the same, the `while (true)` is very common and spreadly used, but after I've seen that the rule allows to achieve the same with with `for (;;)` which I never seen any code using it.

I guess that the rule allows `for (;;)` than `while (true)` because it's easier to parse and keep it the consistency with its name `no-constant-condition`

Thanks for your comments!
