### ISSUE TITLE
promise plugin dependency

### ISSUE THREAD

**Issue by brettz9** [feross/eslint-config-standard#34]
Getting a "Warning: Failed to load plugin promise: Cannot find module 'eslint-plugin-promise'" when referencing standard in my app. I can add it myself, but should it be added to `dependencies` instead of `devDependencies`?

**Comment by feross** [comment]
The correct relationship is actually peer dependency, and it's listed as a peer dependency. See: https://github.com/feross/eslint-config-standard/blob/dddc1b27036bd0d2cd4e310033eb2267dc0dadee/package.json#L50

npm should warn you if you don't have it installed.
