### ISSUE TITLE
Support eslint's new rule format??

### ISSUE THREAD

**Issue by lili21** [feross/eslint-config-standard#38]

**Comment by dcousens** [comment]
@lili21 could you please supply further information?

**Comment by feross** [comment]
@dcousens It seems that @lili21 is referring to this: http://eslint.org/blog/2016/07/eslint-new-rule-format

**Comment by feross** [comment]
I just updated `eslint-plugin-standard` to support the new format: https://github.com/xjamundx/eslint-plugin-standard/pull/11

Thanks for the info, @lili21 !

**Comment by lili21** [comment]
Thanks. @feross
