### ISSUE TITLE
Configuration for rule "no-constant-condition" is invalid

### ISSUE THREAD

**Issue by mweibel** [feross/eslint-config-standard#39]
Having the following dependencies:

```
├── eslint-config-standard@6.0.0-beta.0
├── eslint-plugin-promise@2.0.0
├── eslint-plugin-standard@2.0.0
├── standard@7.1.2
```

I get the following error:

```
» ./node_modules/.bin/eslint src/index.jsx
standard:
	Configuration for rule "no-constant-condition" is invalid:
	Value "[object Object]" has more items than allowed.

Referenced from: /Users/michael/Liip/liiptalk/react-redux-tutorial/.eslintrc
Error: standard:
	Configuration for rule "no-constant-condition" is invalid:
	Value "[object Object]" has more items than allowed.
```

downgrading to `eslint-config-standard@5.3.5` works. However if you just run `npm install --save-dev eslint-config-standard` it will default to using the `6.0.0-beta.0`

**Comment by feross** [comment]
I'll update the npm dist-tag so that `npm install --save-dev eslint-config-standard` doesn't give you the beta version. Thanks for letting me know.

But why are you installing both `standard` and `eslint-config-standard` manually?

**Comment by feross** [comment]
Done.

**Comment by mweibel** [comment]
Great, thanks :)

I followed the howto @ https://github.com/feross/standard/blob/master/docs/webstorm.md

**Comment by brettz9** [comment]
I'm getting the same error with 6.0.1 (with only the following pertaining to eslint):

```json
    "eslint-config-standard": "^6.0.1",
    "eslint-plugin-promise": "^2.0.1",
    "eslint-plugin-standard": "^2.0.0",
```

**Comment by feross** [comment]
@brettz9 What version of eslint are you using? This error happens when your version is not current

**Comment by brettz9** [comment]
`npm list eslint` tells me:

```
+-- UNMET PEER DEPENDENCY eslint@>=3.0.0
+-- UNMET PEER DEPENDENCY grunt@1.0.1
`-- gruntify-eslint@3.1.0
  `-- eslint@3.6.0

npm ERR! peer dep missing: grunt@~0.4.1, required by grunt-wait@0.1.0
npm ERR! peer dep missing: eslint@>=3.0.0, required by eslint-config-standard@6.0.1
```

`npm list eslint -g` tells me just:

```
`-- eslint@3.6.0
```

**Comment by feross** [comment]
Looks like you have an old version of eslint somewhere. Probably version 2.

**Comment by brettz9** [comment]
Yeah, turns out I needed `eslint` as an explicit (larger) peer dependency to avoid npm sticking with the older version it had gotten before. Thanks!

**Comment by Hionstar** [comment]
Hi everyone,

in our project we have a gulp task which runs eslint. With eslint@3.9.1 and eslint-config-standard@6.2.1 I get the error
```
Error: standard:
        Configuration for rule "no-constant-condition" is invalid:
        Value "2,[object Object]" has more items than allowed.
```
for rule
`"no-constant-condition": [2, { "checkLoops": false }]`

Thanks in advance.

**Comment by rafaljanicki** [comment]
@Rapix-x (and any other who may have this error), please check your eslint related dependencies. In my case updating gulp-eslin helped

`gulp list eslint` command may be helpful
