### ISSUE TITLE
no-shadow

### ISSUE THREAD

**Issue by 2color** [feross/eslint-config-standard#42]
Is there a reason why the [no-shadow](http://eslint.org/docs/rules/no-shadow) isn't defined?

This is a pretty common source of errors in code.

**Comment by feross** [comment]
When I first looked at this rule, there was no `allow` option. We want to allow code like:

```js
function read () {
  fs.stat('hi.txt', function (err, stat) {
    if (err) throw err
    fs.readFile('hi.txt', function (err, file) {
      console.log(err, file)
    })
  })
}
```

Note that `err` is shadowed here, and that's okay.

But now that there's an `allow` option, we can try whitelisting `cb`, `callback`, `err`, `error`, `resolve`, `reject`, and `done` and see how many repos fail.

**Comment by feross** [comment]
Even with a whitelist, there are way too many failures with this rule enabled.

```
# tests 422
# pass  313
# fail  109
```

**Comment by dcousens** [comment]
@feross out of interest,  what were some of the example failures?

**Comment by feross** [comment]
Lots of variations on the whitelisted variable names, like `er`, `e`, for `err`. Also `i` and some `j` because of for-loops. Also, all the core node package names, like `path` from people doing:

```js
var path = require('path')
var MY_PATH = path.join(__dirname, 'my', 'path')

// ... lots of intervening lines

function logPath (path) {
  console.log(path)
}
```

It's true this could theoretically catch bugs, but it would also get tripped up by perfectly valid code all the time, so I don't think it's worth it.

**Comment by dcousens** [comment]
`er`, `e` ... gross?
If they are shadowing `i` and `j`,  that sounds like a real possibility for an *actual* bug.
`path`... hmmm... still looks like really bad practice.

**Comment by julien-f** [comment]
IMHO, local code (functions) should not get invalidated by changes of the surrounding code, that's why I really do like shadowing.

Furthermore, I believe that the use cases for shadowing will increase with the new block scope declarations (`const`, `let`).
