### ISSUE TITLE
Eslint broken using standard

### ISSUE THREAD

**Issue by retailos** [feross/eslint-config-standard#45]
Running eslint with standard returns:

> Error: standard:
>        	Configuration for rule "spaced-comment" is invalid:
>        	Value "data["1"].block.balanced" has additional properties.

"eslint": "^2.13.1",
"eslint-config-standard": "^6.0.0",
"eslint-plugin-promise": "^2.0.1",
"eslint-plugin-standard": "^2.0.0",
"standard": "^8.0.0"

**Comment by retailos** [comment]
Solved updating eslint to 3.4.0

**Comment by Flet** [comment]
Yep, `standard` (and `eslint-config-standard`) now requires `eslint` v3.

Here is a little bit more info about the new major version of `standard`:
http://standardjs.com/changelog#800---2016-08-23
