### ISSUE TITLE
Ternary Indentation

### ISSUE THREAD

**Issue by kemitchell** [feross/eslint-config-standard#46]
I see that the rules page shows:

``` javascript
var location = env.development
  ? 'localhost'
  : 'www.api.com'
```

But this will also pass:

``` javascript
var location = env.development
? 'localhost'
: 'www.api.com'
```

In fact, any indentation at all will pass, as long the line breaks appear where they should:

``` javascript
var location = env.development
   ? 'localhost'
       : 'www.api.com'
```

I suppose this is meant to allow the flexibility for:

``` javascript
var lovs8on = env.development
              ? 'localhost'
              : 'www.api.com'
```

Doesn't look like [multiline-ternary](http://eslint.org/docs/rules/multiline-ternary) and [operator-linebreak](http://eslint.org/docs/rules/operator-linebreak) can control indentation.

**Comment by feross** [comment]
@kemitchell Do you mind opening this as an issue on eslint?

**Comment by kemitchell** [comment]
OK.

If eslint-standard-config could require stricter indentation of ternary statements, would it?

**Comment by dcousens** [comment]
@kemitchell we can all hope,  but,  I can forsee breakage.

**Comment by kemitchell** [comment]
@dcousens a good bit of my code, thought of course that's neither here nor there!

**Comment by kemitchell** [comment]
@feross Forgive me if it takes me a while longer to take over to ESLint. They have [much to say about new rule proposals](http://eslint.org/docs/developer-guide/contributing/new-rules), and I want to make sure I respect their guidelines. I get the feeling their answer here may be "write a plugin".

**Comment by dcousens** [comment]
I think this is generic enough that it would be accepted.  But, only 1 way to find out.

**Comment by feross** [comment]
@kemitchell Looks like your suggestion will probably become part of the `indent` rule once it is done being rewritten. Good news!

**Comment by feross** [comment]
Aaand, it looks like ESLint's rewritten `indent` rule is finally complete. I'll open an issue on the main `standard` repo for visibility and discussion. Excited to include this in a future version of `standard`.

**Comment by feross** [comment]
Let's use this issue going forward: https://github.com/feross/standard/issues/735
