### ISSUE TITLE
Does not support eslint 2.0

### ISSUE THREAD

**Issue by QingWei-Li** [feross/eslint-config-standard#47]
Hi,
I get an error with eslint 2.0
```shell
➜  test-standard node_modules/.bin/eslint index.js
standard:
	Configuration for rule "spaced-comment" is invalid:
	Value "data["1"].block.balanced" has additional properties.

Referenced from: /Users/liqingwei/Documents/projects/test/test-standard/.eslintrc.js

➜  test-standard npm list --depth=0
test-standard@1.0.0 /Users/liqingwei/Documents/projects/test/test-standard
├── eslint@2.13.1
├── eslint-config-standard@6.0.0
├── eslint-plugin-promise@2.0.1
└── eslint-plugin-standard@2.0.0
```

my eslintrc
```javascript
module.exports = {
  "extends": "standard",
  "plugins": [
      "standard",
      "promise"
  ]
};
```

I see [`peerDependencies`](https://github.com/feross/eslint-config-standard/blob/master/package.json#L49), It is should support eslint 2.0, right?

**Comment by feross** [comment]
Sorry -- this is incorrect. This config requires eslint 3. We usually update this config to the latest eslint shortly after a new major version of eslint is released, and increment the major version of this config.

If you need to use an older version, you're free to use an older major version `eslint-config-standard`.

PR: https://github.com/feross/eslint-config-standard/pull/48
