### ISSUE TITLE
Having trouble running eslint --fix with this setup

### ISSUE THREAD

**Issue by davestewart** [feross/eslint-config-standard#53]
Hello,

100% likely this is not your setup, but my feeble command line skills.

A project I've joined is set up to lint and warn via gulp, but not fix.

I've attempted to install everything and run, but I get the following on a small test project:

```
Dave $ eslint --fix ./code/* --debug
  eslint:cli Running on files +0ms
  eslint:glob-util Creating list of files to process. +37ms
  eslint:ignored-paths Looking for ignore file in /Users/Dave/test +5ms
  eslint:ignored-paths Could not find ignore file in cwd +0ms
  eslint:cli-engine Processing /Users/Dave/test/code/test.js +7ms
  eslint:cli-engine Linting /Users/Dave/test/code/test.js +1ms
  eslint:config Constructing config for /Users/Dave/test/code/test.js +1ms
  eslint:config Using .eslintrc and package.json files +0ms
  eslint:config Loading /Users/Dave/test/.eslintrc +1ms
  eslint:config-file Loading config file: /Users/Dave/test/.eslintrc +1ms
Cannot find module 'babel-eslint'
Error: Cannot find module 'babel-eslint'
```

I suspect it may be because of a mix of global and local install.

What's the recommended install, setup and commands to run a fix on files in projects?

Thanks

**Comment by dashmug** [comment]
Try not to use your global install.

Instead, use `./node_modules/.bin/eslint --fix ./code/*`.

**Comment by feross** [comment]
Or, you can do the opposite and install `babel-eslint` globally. But @dashmug's solution is preferable.
