### ISSUE TITLE
New wrap-iffe rule breaks semver

### ISSUE THREAD

**Issue by caseyduquettesc** [feross/eslint-config-standard#55]
This new rule syntax is not compatible with existing code and requires updates to other modules in order to work, namely the ones you bumped, eslint and eslint-plugin-promise. Packages that expect patches to be backwards compatible will fail if they list eslint and eslint-plugin-promise as dependencies and don't bump those as well. I'd recommend reverting this change in the 6.2.x branch and posting it in 6.3

```
standard:
    Configuration for rule "wrap-iife" is invalid:
    Value "any,[object Object]" has more items than allowed.
```

**Comment by feross** [comment]
Sorry for the trouble -- I'll try to make sure this doesn't happen in the future.
