### ISSUE TITLE
eslint-index

### ISSUE THREAD

**Issue by wagerfield** [feross/eslint-config-standard#60]
I have created an ESLint utility module that I thought you might find useful.

The module is called `eslint-index` and you can [read the full documentation on npm](https://www.npmjs.com/package/eslint-index).

`eslint-index` provides a great deal of functionality including:
* List all available rules declared by ESLint and any plugins you have included
* Colour code rules depending on their status:
  * `omitted` (not declared anywhere in you ESLint config file)
  * `0|off` (declared, but set to `0|off`)
  * `1|warn`
  * `2|error`
* Display links to the rule documentation page next to each rule
* Filter/reject rules by their `status` and/or their `group`
  * `status` is as described above (`omitted|off|warn|error`)
  * `group` is `eslint` for the core ESLint rules _or_ the name of any of your plugins like `react|import|flowtype`
* Format the output as a `number` or a `table` to get an overview of your rule settings
* Rules that have been marked as `deprecated` are removed from all outputs
* All of the above filters and formatting can be combined, for example:
  * `filter` `omitted` and `off` rules, output them as a `list` and display the rule `doc` links alongside
  * `filter` `eslint` rules and display the rule setting counters in a `table`

I wrote this plugin to aid the development of my own ESLint config settings and found it incredibly useful for keeping track of everything. I hope you find this module useful and please do let me know if you have any ideas on how to improve it.

**Comment by feross** [comment]
Thanks, will give this a try when I start to prepare the `standard` v9 release in the next few months.

**Comment by feross** [comment]
Thanks, just gave this a shot and added it to `standard`'s devDependencies. Super useful!
