### ISSUE TITLE
Relax rules around type-safe equality operator

### ISSUE THREAD

**Issue by chris-kobrzak** [feross/eslint-config-standard#67]
I was wondering if you would be open to the idea of changing the value of the `eqeqeq` rule
from "always" to [smart](http://eslint.org/docs/rules/eqeqeq#smart)?

The reason I would like to see this change in Standard is I believe it makes more sense for the regular
equality operators `==` and `!=` rather than their type-safe counterparts `===` and `!==`  to be used
for `typeof` comparisons. This is because when you use the `typeof` operator you are guaranteed to 
be working with strings so type checks seem a bit superfluous in this context (see [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof)).

As far as performance is concerned, there's virtually no difference between the two flavours of the
 equality operators so this should not be an issue. And as for backwards compatibility, the suggested
change is safe as we are relaxing the existing rule rather than making it stricter. In other words, people
will not need to change their code if we decide to go ahead with it.

**Comment by julien-f** [comment]
Why adding a special case for the dev when the `===` can be used everywhere?

**Comment by feross** [comment]
Isn't it easier to remember to always use `===`? I don't see what this gains us. It works just fine to do `typeof myVar === 'string'` and it means there's only way to do things.

**Comment by dcousens** [comment]
`===` everywhere is easier than remembering more rules.

**Comment by chris-kobrzak** [comment]
Hi guys, many thanks for responding so promptly.

I must admit it's pretty hard for me to understand the "easiness" argument as using linters is all about being more self-disciplined, putting more effort in how you write the code, giving more focus to quality etc. so if anything, linters seem to be more about making our lives somewhat _harder_, at least in the short run :smile:

The issue I have with the current configuration of the `eqeqeq` rule is it prohibits me from writing code that is perfectly valid and arguably makes more sense:

```javascript
// most expedient thing to do but Standard thinks it's wrong:
if (typeof foo == 'string') {}

// a bit sloppy approach but the only one Standard allows you to follow:
if (typeof foo === 'string') {}
```
And just because it makes perfect sense and indeed in most cases is simply preferred to resort to the type-safe equality operators `===` and `!==`, we shouldn't IMHO completely disallow the other operators for the sake of "using it everywhere". As I mentioned earlier, `typeof` always returns a string so confirming the type is in fact a string just seems a bit over the top.

I just think enabling the `smart` option available in ESlint would make Standard... well, a little smarter :smile:

**Comment by julien-f** [comment]
I don't see why `==` makes more sense…

Anyway, standard is about homogeneity, that's why some styles are enforced even though other approaches might be correct

**Comment by dcousens** [comment]
@chris-kobrzak I can write standard compliant code,  without running `standard`.
This rule would only server to confuse.
