### ISSUE TITLE
Parsing error when I use destructuring in a  function signature 

### ISSUE THREAD

**Issue by LeandroZacarias** [feross/eslint-config-standard#68]
When I use destructuring in a  function signature I got this error:

`[eslint] Parsing error: Illegal 'use strict' directive in function with non-simple parameter list`

> Example:

` getAvailabilitiesOneWay ({ origin, destination, departureDate, valueComposition }) {
   ...
}`

**Comment by feross** [comment]
Can you share a complete, minimal example that reproduces the issue?

**Comment by LinusU** [comment]
🤔 I saw this a few days ago, I think that the problem was with acorn, and the bug has already been fixed there...

If you remove your `node_modules` and run `npm install` again it should hopefully work. Also make sure that you are using the latest version of standard

**Comment by LeandroZacarias** [comment]
Thank you guys! 

This solved my problem.

**Comment by LinusU** [comment]
Great!
