### ISSUE TITLE
Depend directly on eslint-plugin-standard and eslint-plugin-promise

### ISSUE THREAD

**Issue by maxnordlund** [feross/eslint-config-standard#72]
I found it strange to have to install three different packages, instead of just one. Then I noticed they are specified as dependencies in `package.json`, albeit as peer dependencies.

Why can't they be just normal dependencies, and isn't peer dependencies [deprecated](https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/)?

**Comment by LinusU** [comment]
Hi Max 👋 long time no see 😄 

I believe that the reason for this is so that we can bump the version of `eslint-plugin-standard` and `eslint-plugin-promise` in `standard` without having to cut a new release of `eslint-config-standard`. I have also noticed this though and it might be a good idea to revisit this and weigh the pros and cons...

paging @feross :)

**Comment by feross** [comment]
I would love to make this change, but ESLint would need to support it directly. See issue here: https://github.com/eslint/eslint/issues/3458

We could just add them as dependencies, but then you'd be relying on the npm3 flattening behavior that puts all packages in the top-level to make the plugin "findable" by eslint, which only looks for plugins in the top-level `node_modules` folder. If flattening didn't happen for a plugin for whatever reason (maybe another package somehow depending on the same plugin), then you'd be missing a dependency. Also, this wouldn't work at all for npm2 users.

**Comment by maxnordlund** [comment]
> Hi Max 👋 long time no see 😄
Indeed, 😸, you show up like the old man in a box.

> I would love to make this change, but ESLint would need to support it directly. See issue here: eslint/eslint#3458
There seems to have been some moment there fairly recently, e.g. last december, and they are looking for a volunteer to switch to plugin shipping configs, rather then a config shipping plugins.

Would you mind trying it out? (I'm not familiar enough with how to do that I'm afraid)

**Comment by mightyiam** [comment]
Reopen?

**Comment by mightyiam** [comment]
https://github.com/standard/eslint-config-standard/pull/91

**Comment by Flet** [comment]
It looks like https://github.com/eslint/eslint/issues/3458 is still unresolved. Has something changed?

**Comment by mightyiam** [comment]
Nah. I didn't realize this is still an issue. I thought it would have been solved by npm by now. I'm following that issue.
