### ISSUE TITLE
Add ChangeLog

### ISSUE THREAD

**Issue by ai** [feross/eslint-config-standard#75]
Thanks for awesome project, it is my favorite ESLint config. What do you think about adding ChangeLog to it?

We with many other developers think that having ChangeLog is very important for every open source project: http://keepachangelog.com/en/0.3.0/

Of course, users can look into commits, but:

1. It requires more time, to open every commit.
2. Commits will be split to “breaking changes” or “add features”.

I know that maintaining big project need a lot of time (by my experience with PostCSS and Autoprefixer). And you always try to reduce maintaining time. But `eslint-config-standard` releases is rare. I keep ChangeLog in my every project :).

@feross What do you think?

**Comment by Flet** [comment]
For what its worth, a very detailed changelog kept on feross/standard: https://github.com/feross/standard/blob/master/CHANGELOG.md

**Comment by ai** [comment]
Great, thanks for link.

Copy here will be very nice. Or just CHANGELOG file with a link.

**Comment by feross** [comment]
Done in https://github.com/feross/eslint-config-standard/commit/df2400a95faf952b5b8469f509809942755a2342
