### ISSUE TITLE
Clarify versioning

### ISSUE THREAD

**Issue by szdavid92** [feross/eslint-config-standard#77]
Please clarify how this package follows the versioning of 'standard'. After the major version upgrade from 6 to 7, the newly enforced no-unused-expressions rule affected me. At first I didn't understand why, as that rule was introduced in standard/v9, and it wasn't obvious to me that this package enforces standard/v7 until I looked at the actual commits.

So, please clarify this.

**Comment by feross** [comment]
I wonder if we should just skip v8 and v9 and release `eslint-config-standard` v10 when `standard` v10 comes out? Then we could keep the major versions in sync from v10 forward.

That way users of `eslint-config-standard` can refer to the `standard` changelog to read about changes.

**Comment by Flet** [comment]
Syncing up the major versions is probably OK. Its not really how semver is intended to be used, but it feels right and its easier to consume if folks are transitioning from `standard` to the raw config.

They *should* stay in sync, however the versions might diverge again if `standard` has some breaking change not triggered by this package. This can be dealt with if it ever comes up, but it could ruffle feathers.

👍

**Comment by feross** [comment]
Alright, published the latest 8.x beta as 8.0.0 and also as 10.0.0.

In the future, we'll try to keep the major version of `eslint-config-standard` in sync with the major version of `standard`.
