### ISSUE TITLE
v10 requires eslint-plugin-standard >= 2.1.0

### ISSUE THREAD

**Issue by ifraixedes** [feross/eslint-config-standard#79]
I found that the [eslint-plugin-standard version in the peerDependencies](https://github.com/feross/eslint-config-standard/blob/master/package.json#L55) should be `>=2.1.0` because standard v10 requires the `non-callback-literal` rule which was added after the [version 2.0.1](https://github.com/xjamundx/eslint-plugin-standard/tree/v2.0.1)

**Comment by feross** [comment]
@ifraixedes Thanks, this should be fixed in the latest version!
