### ISSUE TITLE
UNMET PEER DEPENDENCY (reopened)

### ISSUE THREAD

**Issue by vietnogi** [feross/eslint-config-standard#80]
`npm install eslint-config-standard` causes `UNMET PEER DEPENDENCY eslint@>=3.8.1` however, the latest version of eslint is `v3.19.0`, https://github.com/eslint/eslint/releases

**Comment by feross** [comment]
This message means that you need to install `eslint` and it must be at least version 3.8.1. You haven't done that, and that is why you are getting a message.
