### ISSUE TITLE
The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.

### ISSUE THREAD

**Issue by donovanhiland** [feross/eslint-config-standard#83]

**Comment by Flet** [comment]
hey @donovanhiland thanks for reporting! `standard` combines the eslint config from here with the jsx specific config at https://github.com/feross/eslint-config-standard-jsx

It looks like is particular rule is coming from that packge. I recreated the issue over there! 👍

**Comment by donovanhiland** [comment]
Awesome. Saw there were plans/hopes to merge that into the main standard so I wasn't sure. Thanks!

**Comment by iandunn** [comment]
xref: https://github.com/standard/eslint-config-standard-jsx/issues/23

**Comment by provDeepakAhuja** [comment]
Hi,
I am getting this error still.. even after adding the rule.. any other pointer..

The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.
Cannot read property 'range' of null

Below is my .eslintrc
{
"extends": ["standard", "standard-react"],
"globals": {
"**DEVELOPMENT**": true,
"**CLIENT**": true,
"**DEVTOOLS**": true,
"**DISABLE_SSR**": true,
"fetch": false,
"fail": false,
"test": false,
"describe": false,
"expect": false,
"jest": false,
"afterAll": false,
"beforeAll": false,
"afterEach": false,
"beforeEach": false
},
"rules": {
"indent" : ["error", 2, { "ignoredNodes": ["JSXElement *"] }],
"object-curly-spacing": ["error", "always", { "objectsInObjects": false }],
"standard/object-curly-even-spacing": "off",
"jsx-quotes": ["error", "prefer-double"],
"react/jsx-tag-spacing": ["error", { "beforeSelfClosing": "always" }],
"react/jsx-curly-spacing": [2, "never", {"allowMultiline": true}],
"react/jsx-indent-props": ["error", 4],
"no-unused-expressions": "off"
},
"settings": {
"react": {
"version": "latest"
}
},
"parser": "babel-eslint"
}
